language: ruby

rvm:
  - 3.0.2

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE tennis_club_test;'
  - psql -U postgres tennis_club_test < db/migrations/create_tables.sql

script:
  - bundle exec rspec
